import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { generateAIPersonalPlan } from '@/lib/ai/plan';

export const useAIPlanGeneration = () => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateAndSavePlan = async () => {
    if (!user) {
      throw new Error('User not authenticated');
    }

    setLoading(true);
    setError(null);

    try {
      // Generate AI plan
      const { plan } = await generateAIPersonalPlan({ userId: user.id });

      // Save plan to database as a program
      const { data, error: saveError } = await supabase
        .from('programs')
        .insert({
          name: plan.summary || 'AI Generated Plan',
          description: `Personalized ${plan.weeks || 4}-week plan generated by AI`,
          status: 'active',
          category: 'fitness', // Default to fitness, could be made dynamic
          coach_id: user.id, // For now, assign to user as self-coach
          assigned_to: user.id,
          scheduled_date: new Date().toISOString(),
          plan: plan,
          is_ai_generated: true
        })
        .select()
        .single();

      if (saveError) throw saveError;

      return data;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate AI plan';
      setError(errorMessage);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  return {
    generateAndSavePlan,
    loading,
    error
  };
};
