// File: src/mockdata/landingpage/plans.js
export const PLANS = [
  {
    name: 'Premium',
    price: '$29.99',
    period: 'month',
    summary: 'Everything you need to transform',
    ctaText: 'Choose Premium - $29.99/mo',
    planKey: 'premium',
    popular: true,
    gradient: 'from-orange-100 to-orange-50',
    features: [
      { text: '💪 Fitness, Nutrition & Mental Plans', included: true },
      { text: '📚 Full Knowledge Hub', included: true },
      { text: '🍳 Recipe + Exercise Library', included: true },
      { text: '📖 Blog Access', included: true },
      { text: '📊 Progress Tracking', included: true },
      { text: '👨‍💼 Coach Feedback', included: true },
      { text: '🔄 Monthly Plan Updates', included: true },
    ],
  },
  {
    name: 'Standard',
    price: '$14.99',
    period: 'month',
    summary: 'Perfect for focused goals',
    ctaText: 'Try Standard - 14 Days Free',
    planKey: 'standard',
    popular: false,
    gradient: 'from-blue-100 to-blue-50',
    features: [
      { text: '🎯 One monthly plan (choose fitness, nutrition or mental)', included: true },
      { text: '📚 Knowledge Hub', included: true },
      { text: '🍳 Recipe/Exercise Library', included: true },
      { text: '📖 Blog Access', included: true },
      { text: '📊 Progress Tracking', included: false },
      { text: '👨‍💼 Feedback', included: false },
      { text: '✨ 14-Day Free Trial', included: true, highlight: true },
    ],
  },
  {
    name: 'Basic',
    price: '$17.99',
    period: 'One-Time',
    summary: 'Get started with essentials',
    ctaText: 'Buy Basic - $17.99 One-Time',
    planKey: 'basic',
    popular: false,
    gradient: 'from-gray-100 to-gray-50',
    features: [
      { text: '📅 One 1-month plan', included: true },
      { text: '📖 Blog Access', included: true },
      { text: '📚 Knowledge Hub', included: false },
      { text: '🍳 Library', included: false },
      { text: '📊 Tracking or Feedback', included: false },
      { text: '🔄 Plan updates', included: false },
    ],
  },
];
