// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { config } from '@/lib/config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(config.supabase.url, config.supabase.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});