// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bhmdxxsdeekxmejnjwin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobWR4eHNkZWVreG1lam5qd2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTAzMzcsImV4cCI6MjA3MDc2NjMzN30.N3aDfjRlinKAXN3DMAAy9jGK3j8SsM1V5-zpYE1SRKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});